services:
  - type: web
    name: vocallocal
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y portaudio19-dev python3-pyaudio
      pip install --upgrade pip
      pip install -r requirements.txt
      chmod +x postbuild.sh
      ./postbuild.sh
    startCommand: bash ./start.sh
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
    # Add this section to ensure HTTPS is enforced
    headers:
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
