services:
  - type: web
    name: vocallocal
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg portaudio19-dev python3-pyaudio
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install -r requirements_render.txt
      chmod +x postbuild.sh
      ./postbuild.sh
    startCommand: bash ./start.sh
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FIREBASE_DATABASE_URL
        value: https://vocal-local-e1e70-default-rtdb.firebaseio.com
      - key: FIREBASE_CREDENTIALS
        sync: false
      - key: GUNICORN_CMD_ARGS
        value: "--worker-class gthread --threads 4 --timeout 120 --graceful-timeout 120"
      - key: INPUT_PATH
        value: /tmp/input
      - key: OUTPUT_DIR
        value: /tmp/output
      - key: CHUNK_SECONDS
        value: "300"
    # Add this section to ensure HTTPS is enforced
    headers:
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
