services:
  - type: web
    name: vocallocal
    env: python
    buildCommand: |
      chmod +x build.sh
      ./build.sh
    startCommand: bash ./start.sh
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true