services:
  - type: web
    name: vocallocal
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y portaudio19-dev python3-pyaudio
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install google-generativeai>=0.8.5
      pip install google-api-core google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib googleapis-common-protos protobuf
    startCommand: bash ./start.sh
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true