"""
Language utility functions for VocalLocal
"""

def get_language_name_from_code(language_code):
    """Helper function to get language name from language code"""
    # Dictionary mapping language codes to language names
    language_map = {
        "en": "English",
        "es": "Spanish",
        "fr": "French",
        "de": "German",
        "it": "Italian",
        "pt": "Portuguese",
        "nl": "Dutch",
        "ja": "Japanese",
        "zh": "Chinese",
        "ko": "Korean",
        "ru": "Russian",
        "ar": "Arabic",
        "hi": "Hindi",
        "tr": "Turkish",
        "sv": "Swedish",
        "pl": "Polish",
        "no": "Norwegian",
        "fi": "Finnish",
        "da": "Danish",
        "uk": "Ukrainian",
        "cs": "Czech",
        "ro": "Romanian",
        "hu": "Hungarian",
        "el": "Greek",
        "he": "Hebrew",
        "te": "Telugu",
        "th": "Thai",
        "vi": "Vietnamese",
        "id": "Indonesian",
        "ms": "Malay",
        "bg": "Bulgarian",
        "ur": "Urdu",
        "bn": "Bengali",
        "fa": "Persian",
        "sw": "Swahili",
        "ta": "Tamil",
        "pa": "Punjabi",
        "mr": "Marathi",
        "gu": "Gujarati",
        "kn": "Kannada",
        "ml": "Malayalam",
        "ne": "Nepali",
        "si": "Sinhala",
        "km": "Khmer",
        "lo": "Lao",
        "my": "Burmese",
        "ps": "Pashto",
        "am": "Amharic",
        "az": "Azerbaijani",
        "kk": "Kazakh",
        "sr": "Serbian",
        "tg": "Tajik",
        "uz": "Uzbek",
        "yo": "Yoruba",
        "zu": "Zulu",
        "wuu": "Wu Chinese",
        "ha": "Hausa",
        "yue": "Cantonese",
        "or": "Odia",
        "as": "Assamese",
        "nan": "Min Nan Chinese",
        "ku": "Kurdish",
        "ig": "Igbo"
    }
    
    # Return the language name if found, otherwise return the code
    return language_map.get(language_code, language_code)

def get_supported_languages():
    """Return a dictionary of supported languages with their codes and native names"""
    supported_languages = {
        "English": {"code": "en", "native": "English"},
        "Spanish": {"code": "es", "native": "Español"},
        "French": {"code": "fr", "native": "Français"},
        "German": {"code": "de", "native": "Deutsch"},
        "Italian": {"code": "it", "native": "Italiano"},
        "Portuguese": {"code": "pt", "native": "Português"},
        "Dutch": {"code": "nl", "native": "Nederlands"},
        "Japanese": {"code": "ja", "native": "日本語"},
        "Chinese": {"code": "zh", "native": "中文"},
        "Korean": {"code": "ko", "native": "한국어"},
        "Russian": {"code": "ru", "native": "Русский"},
        "Arabic": {"code": "ar", "native": "العربية"},
        "Hindi": {"code": "hi", "native": "हिन्दी"},
        "Turkish": {"code": "tr", "native": "Türkçe"},
        "Swedish": {"code": "sv", "native": "Svenska"},
        "Polish": {"code": "pl", "native": "Polski"},
        "Norwegian": {"code": "no", "native": "Norsk"},
        "Finnish": {"code": "fi", "native": "Suomi"},
        "Danish": {"code": "da", "native": "Dansk"},
        "Ukrainian": {"code": "uk", "native": "Українська"},
        "Czech": {"code": "cs", "native": "Čeština"},
        "Romanian": {"code": "ro", "native": "Română"},
        "Hungarian": {"code": "hu", "native": "Magyar"},
        "Greek": {"code": "el", "native": "Ελληνικά"},
        "Hebrew": {"code": "he", "native": "עברית"},
        "Telugu": {"code": "te", "native": "తెలుగు"},
        "Thai": {"code": "th", "native": "ไทย"},
        "Vietnamese": {"code": "vi", "native": "Tiếng Việt"},
        "Indonesian": {"code": "id", "native": "Bahasa Indonesia"},
        "Malay": {"code": "ms", "native": "Bahasa Melayu"},
        "Bulgarian": {"code": "bg", "native": "Български"},
        "Urdu": {"code": "ur", "native": "اردو"},
        "Bengali": {"code": "bn", "native": "বাংলা"},
        "Persian": {"code": "fa", "native": "فارسی"},
        "Swahili": {"code": "sw", "native": "Kiswahili"},
        "Tamil": {"code": "ta", "native": "தமிழ்"},
        "Punjabi": {"code": "pa", "native": "ਪੰਜਾਬੀ"},
        "Marathi": {"code": "mr", "native": "मराठी"},
        "Gujarati": {"code": "gu", "native": "ગુજરાતી"},
        "Kannada": {"code": "kn", "native": "ಕನ್ನಡ"},
        "Malayalam": {"code": "ml", "native": "മലയാളം"},
        "Nepali": {"code": "ne", "native": "नेपाली"},
        "Sinhala": {"code": "si", "native": "සිංහල"},
        "Khmer": {"code": "km", "native": "ខ្មែរ"},
        "Lao": {"code": "lo", "native": "ລາວ"},
        "Burmese": {"code": "my", "native": "မြန်မာ"},
        "Pashto": {"code": "ps", "native": "پښتو"},
        "Amharic": {"code": "am", "native": "አማርኛ"},
        "Azerbaijani": {"code": "az", "native": "Azərbaycan dili"},
        "Kazakh": {"code": "kk", "native": "Қазақ тілі"},
        "Serbian": {"code": "sr", "native": "Српски"},
        "Tajik": {"code": "tg", "native": "Тоҷикӣ"},
        "Uzbek": {"code": "uz", "native": "O'zbek"},
        "Yoruba": {"code": "yo", "native": "Yorùbá"},
        "Zulu": {"code": "zu", "native": "isiZulu"},
        "Wu Chinese": {"code": "wuu", "native": "吴语"},
        "Hausa": {"code": "ha", "native": "هَوُ"},
        "Cantonese": {"code": "yue", "native": "粵語"},
        "Odia": {"code": "or", "native": "ଓଡ଼ିଆ"},
        "Assamese": {"code": "as", "native": "অসমীয়া"},
        "Min Nan Chinese": {"code": "nan", "native": "閩南語"},
        "Kurdish": {"code": "ku", "native": "Kurdî"},
        "Igbo": {"code": "ig", "native": "Igbo"}
    }
    return supported_languages
